CarzRideOn/CarzRideOn/urls.py

from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'', include('website.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CarzRideOn/website/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name="index_page"),
    url(r'^offerrides/$', views.offer_ride, name="offer_ride"),
    url(r'^takerides/$', views.take_ride, name="take_ride"),
    url(r'^view_requests/$', views.view_requests, name="view_requests"),
    url(r'^profile/$', views.view_profile, name="view_profile"),
    url(r'^update_profile/$', views.update_profile, name="update_profile"),
    url(r'^request_ride/(?P<ride_id>\d+)/$', views.request_ride, name="request_ride"),
    url(r'^contact_us/$', views.contact_us, name="contact_us"),
    url(r'^validate_request/(?P<request_id>\d+)/$', views.validate_ride_request, name="validate_ride_request"),
    url(r'^view_rides/$', views.view_user_rides, name="view_user_rides"),
    url(r'^cancel_ride/(?P<ride_id>\d+)/$', views.cancel_ride, name="cancel_ride"),
    url(r'^edit_ride/(?P<ride_id>\d+)/$', views.edit_rides, name="edit_ride"),
]

CarzRideOn/website/models.py
from django.contrib.auth.models import PermissionsMixin, User
from django.db import models
from django.contrib.auth.models import User


class Contactus(models.Model):
    fb_id = models.CharField(max_length=100, blank=True, null=True)
    type = models.CharField(max_length=11, blank=True, null=True)
    message = models.TextField(blank=True, null=True)
    attachment_url = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        db_table = 'contactus'


class Ratings(models.Model):
    rate = models.CharField(max_length=100, blank=True, null=True)
    fb_id = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        # managed = False
        db_table = 'ratings'


class Rides(models.Model):
    fb_id = models.CharField(max_length=100, blank=True, null=True)
    car_model = models.CharField(max_length=100, blank=True, null=True)
    seats = models.CharField(max_length=100, blank=True, null=True, db_column='seats')
    seats_available = models.IntegerField(db_column='seats_available')
    cost = models.CharField(max_length=10, blank=True, null=True, db_column='cost')
    source = models.CharField(max_length=200, blank=True, null=True, db_column='source')
    source_latitude = models.CharField(max_length=100, blank=True, null=True, db_column='source_latitude')
    source_longitude = models.CharField(max_length=100, blank=True, null=True, db_column='source_longitude')
    destination = models.CharField(max_length=200, blank=True, null=True, db_column='destination')
    destination_latitude = models.CharField(max_length=100, blank=True, null=True, db_column='destination_latitude')
    destination_longitude = models.CharField(max_length=100, blank=True, null=True, db_column='destination_longitude')
    dateofride = models.CharField(max_length=20, blank=True, null=True, db_column='dateofride')
    start_time = models.CharField(max_length=100, blank=True, null=True, db_column='start_time')
    created_at = models.DateTimeField(db_column='created_at')
    message = models.TextField(blank=True, null=True, db_column='message')
    ridecancelstatus = models.IntegerField(db_column='rideCancelStatus')  # Field name made lowercase.

    class Meta:
        db_table = 'rides'


class UserRides(models.Model):
    fb_id = models.CharField(max_length=100, blank=True, null=True)
    task_id = models.CharField(max_length=100, blank=True, null=True)
    status = models.CharField(max_length=1, blank=True, null=True)
    created_at = models.CharField(max_length=1000)
    message = models.CharField(max_length=1000, blank=True, null=True)

    class Meta:
        db_table = 'user_rides'


# Create your models here.
class CustomUser(models.Model):
    sno = models.AutoField(primary_key=True)
    fb_id = models.CharField(max_length=100, blank=True, null=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    email = models.CharField(max_length=100, blank=True, null=True, unique=True, default="")
    mobile = models.CharField(max_length=100, blank=True, null=True)
    gender = models.CharField(max_length=100, blank=True, null=True)
    dob = models.CharField(max_length=100, blank=True, null=True)
    ref_number = models.CharField(max_length=100, blank=True, null=True)
    ref_status = models.CharField(max_length=100)
    created_at = models.DateTimeField()
    api_key = models.CharField(max_length=32, blank=True, null=True)
    fcm_id = models.CharField(max_length=1000, blank=True, null=True)
    company = models.CharField(max_length=100)
    aadhar = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        db_table = 'users'

CarzRideOn/website/forms.py
import datetime
from django import forms
from .models import Rides, CustomUser, UserRides, Contactus


class RidesForm(forms.ModelForm):
    car_model = forms.CharField(max_length=100)
    seats = forms.CharField(max_length=10)
    seats_available = forms.IntegerField()
    cost = forms.CharField(max_length=10)
    start_time = forms.CharField(max_length=100)
    dateofride = forms.CharField(max_length=100)
    message = forms.TextInput()
    source_location = forms.CharField(max_length=1000)
    sou_lati = forms.CharField(max_length=1000)
    sou_long = forms.CharField(max_length=1000)
    des_lati = forms.CharField(max_length=1000)
    des_long = forms.CharField(max_length=1000)
    destination_location = forms.CharField(max_length=1000)

    class Meta:
        model = Rides
        fields = ['car_model', 'seats', 'seats_available', 'cost', 'start_time', 'dateofride', 'message', ]


class UpdateProfileForm(forms.ModelForm):
    gender = forms.CharField(max_length=100)
    dob = forms.CharField(max_length=100)
    mobile = forms.CharField(max_length=100)
    company = forms.CharField(max_length=100)
    ref_number = forms.CharField(max_length=100)
    aadhar = forms.CharField(max_length=100)
    fcm_id = forms.CharField(max_length=1000)

    class Meta:
        model = CustomUser
        fields = ['gender', 'dob', 'mobile', 'company', 'ref_number', 'aadhar', 'fcm_id',]


class SearchRideForm(forms.Form):
    source_location = forms.CharField(max_length=1000)
    sou_lati = forms.CharField(max_length=1000)
    sou_long = forms.CharField(max_length=1000)
    des_lati = forms.CharField(max_length=1000)
    des_long = forms.CharField(max_length=1000)
    destination_location = forms.CharField(max_length=1000)


class RequestRideForm(forms.ModelForm):
    message = forms.TextInput()

    class Meta:
        model = UserRides
        fields = ['message', ]


VALIDATE_REQUEST_CHOICES = (
    ('2', 'Accept'),
    ('3', 'Reject'),
)


class ValidateRequestForm(forms.Form):
    validation = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        choices=VALIDATE_REQUEST_CHOICES,
    )


MESSAGE_TYPE_CHOICES = (
    ('Complaint', 'Complaint'),
    ('Query', 'Query'),
    ('Feedback', 'Feedback'),
)


class ContactForm(forms.ModelForm):
    type = forms.ChoiceField(
        required=True,
        widget=forms.Select(),
        choices=MESSAGE_TYPE_CHOICES,
    )
    image_url = forms.CharField(max_length=1000)
    message = forms.TextInput()

    class Meta:
        model = Contactus
        fields = ['type', 'message', 'image_url', ]

CarzRideOn/templates/website/contact_us.html
{% extends 'website/base.html' %}

{% block content %}
    <div class="container padded-container">
        <form class="form-login" method="post" action="#">
            {% csrf_token %}
            <div class="form-log-in-with-email">
                <div class="form-white-background">
                    <div class="form-title-row">
                        <h1>Contact Us</h1>
                    </div>
                    <div class="form-row">
                        <label>
                            <span>Reason</span>
                            <select name="type" id="id_type">
                                <option selected>Select Reason</option>
                                <option value="Complaint">Complaint</option>
                                <option value="Query">Query</option>
                                <option value="Feedback">Feedback</option>
                            </select>
                        </label>
                    </div>
                    <div class="form-row">
                        <label>
                            <span>Message</span>
                            <textarea name="message" placeholder="Enter Message" id="id_message"></textarea>
                        </label>
                    </div>
                    <div class="form-row">
                        <label>
                            <span>Attachment</span>
                            <input type="text" id="id_image_url" placeholder="Enter URL" name="image_url">
                        </label>
                    </div>
                    <div class="form-row">
                        <button type="submit" class="btn">Submit</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

CarzRideOn/templates/website/edit_ride.html
{% extends "website/base.html" %}

{% block content %}

<div class="container padded-container">
    <form class="form-login" method="post" action="#" id="offerrideform">
        {% csrf_token %} 
        <div class="input-group">
            <input type="hidden" name="sou_lati" id="id_sou_lati" value = "{{ selected_ride.source_latitude }}"/>
        </div>
        
        <div class="input-group">
            <input type="hidden" name="sou_long" id="id_sou_long" value = "{{ selected_ride.source_longitude }}"/>
        </div>
        
        <div class="input-group">
            <input type="hidden" name="des_lati" id="id_des_lati" value = "{{ selected_ride.destination_latitude }}"/>
        </div>
        
        <div class="input-group">
            <input type="hidden" name="des_long" id="id_des_long" value = "{{ selected_ride.destination_longitude }}"/>
        </div>
        <div class="form-log-in-with-email">
            <div class="form-white-background">
                <div class="form-title-row">
                    <h1>Update Ride</h1>
                </div>
                <div class="form-row">
                    <label>
                        <span>Car Model</span>
                        <input type="text" id="id_car_model" placeholder="Enter Car Model" name="car_model" value = "{{ selected_ride.car_model }}">
                    </label>
                </div>
                <div class="form-row">
                    <label>
                        <span>Seats</span>
                        <input type="text" id="id_seats" placeholder="Enter No. of Seats" name="seats" value = "{{ selected_ride.seats }}">
                    </label>
                </div>
                <div class="form-row">
                    <label>
                        <span>Seats Available</span>
                        <input type="text" id="id_seats_available" placeholder="Enter No. of Seats Available" name="seats_available" value = "{{ selected_ride.seats_available }}">
                    </label>
                </div>
                <div class="form-row">
                    <label>
                        <span>Cost</span>
                        <input type="text" id="id_cost" placeholder="Enter Cost" name="cost" value = "{{ selected_ride.cost }}">
                    </label>
                </div>
                <div class="form-row">
                    <label>
                        <span>Start Time</span>
                        <input type="time" id="id_start_time" placeholder="Enter Start Time" name="start_time" value = "{{ selected_ride.start_time }}">
                    </label>
                </div>
                <div class="form-row">
                    <label>
                        <span>Date Of Ride</span>
                        <input type="date" id="id_dateofride" name="dateofride" value = "{{ selected_ride.dateofride }}">
                    </label>
                </div>
                <div class="form-row">
                    <label>
                        <span>Message</span>
                        <textarea name="message" placeholder="Enter Message" id="id_message">{{ selected_ride.message }}</textarea>
                    </label>
                </div>
                <div class="form-row">
                    <label>
                        <span>Source Location</span>
                        <input type="text" name="source_location" maxlength="1000" required="" placeholder="Select Location Below" id="id_source_location" value = "{{ selected_ride.source }}">
                    </label>
                </div>
                <button type="button" id="source_location_button" style="margin-top: -20px;" data-toggle="modal" data-target="#myModal">Source</button>
                <div class="form-row">
                    <label>
                        <span>Destination Location</span>
                        <input type="text" name="destination_location" maxlength="1000" required="" placeholder="Select Location Below" id="id_destination_location" value = "{{ selected_ride.destination }}">
                    </label>
                </div>
                <button type="button" id="destination_location_button" style="margin-top: -20px;" data-toggle="modal" data-target="#myModal">Destination</button>
                <div class="form-row">
                    <button type="submit" class="btn">Update</button>
                </div>
            </div>
        </div>
    </form>
</div>
<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h4 class="modal-title">Select Location</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <div class="pac-card" id="pac-card">
                    <div id="pac-container">
                        <input id="location_input" type="text" placeholder="Enter a location">
                    </div>
                </div>
                <div id="map"></div>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>

{% endblock content %}

CarzRideOn/templates/website/index.html
{% extends 'website/base.html' %}

{% load staticfiles %}

{% block content %}

    <header class=" text-white">
      <div class="container text-center" style="color: black; font-family: 'Bree Serif',serif;">
        <h1 style="font-weight: 500;">Welcome to Carz Ride On</h1>
        <p class="lead" style="font-weight: 700;">Intra &amp; Inter-City Car Pooling</p>
      </div>
    </header>

    {% if custom_notifications %}
        <script>
            $.notify({
                message: '{{ custom_notifications }}',
                type: 'success'
            });
        </script>
    {% endif %}

    <section id="about" class="bg-white">
        <div class="container">
            <div class="row">
                <div class="col-lg-6" id="about-left">
                    <br>
                    <br>
                    <h2 style="font-weight: 700;">About Us</h2>
                    <p class="lead sub-heading">Are you travelling alone? Do you want to TAKE or OFFER Ride?</p>
                    <p>Carz Ride On App simplifies your travel. You can offer ride and can take ride so that you can save your money and fuel for an Eco Friendly Environment! We provide Intra and Inter-city rides. Offer or Take rides from your source to destination of your journey.</p>
                </div>
                <div class="col-lg-6" id="about-right">
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/K6F7wwcF-iM" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="services" class="bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <h2 style="font-weight: 700;">Services We Offer</h2>
                    <br>
                    <div class="sub-heading-div">
                        <p class="lead sub-heading">Take Ride</p>
                        <p>Select your starting point from where you would like to travel and the destination point on which date is your journey. Select the most relevant rides.</p>
                    </div>
                    <div class="sub-heading-div">
                        <p class="lead sub-heading">Offer Ride</p>
                        <p>Enter your source and destination of your journey.Specifying date,time,car-model,number of seats and cost per seat. With a personalized message.With this you have successfully offer a ride.</p>
                    </div>
                    <div class="sub-heading-div">
                        <p class="lead sub-heading">References</p>
                        <p>At the time of registration you have to provide mobile number of your reference. This has to be approved by the reference which you have provided. This makes a rider or traveller more trust worthy.</p>
                    </div>
                    <div class="sub-heading-div">
                        <p class="lead sub-heading">Contact Us</p>
                        <p>If you like to give feedback/query/complaint you can always submit along with the screenshots if you have any.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

CarzRideOn/templates/website/offerride.html
{% extends 'website/base.html' %}
{% block content %}
    <div class="container padded-container">
        <form class="form-login" method="post" action="#" id="offerrideform">
            {% csrf_token %}
            {% for field in form %}
                {% if "lati" in field.label_tag or "long" in field.label_tag %}
                    <div class="input-group">
                        {{ field.as_hidden }}
                    </div>
                {% endif %}
            {% endfor %}
            <div class="form-log-in-with-email">
                <div class="form-white-background">
                    <div class="form-title-row">
                        <h1>Offer Ride</h1>
                    </div>
                    <div class="form-row">
                        <label>
                            <span>Car Model</span>
                            <input type="text" id="id_car_model" placeholder="Enter Car Model" name="car_model">
                        </label>
                    </div>
                    <div class="form-row">
                        <label>
                            <span>Seats</span>
                            <input type="text" id="id_seats" placeholder="Enter No. of Seats" name="seats">
                        </label>
                    </div>
                    <div class="form-row">
                        <label>
                            <span>Seats Available</span>
                            <input type="text" id="id_seats_available" placeholder="Enter No. of Seats Available" name="seats_available">
                        </label>
                    </div>
                    <div class="form-row">
                        <label>
                            <span>Cost</span>
                            <input type="text" id="id_cost" placeholder="Enter Cost" name="cost">
                        </label>
                    </div>
                    <div class="form-row">
                        <label>
                            <span>Start Time</span>
                            <input type="time" id="id_start_time" placeholder="Enter Start Time" name="start_time">
                        </label>
                    </div>
                    <div class="form-row">
                        <label>
                            <span>Date Of Ride</span>
                            <input type="date" id="id_dateofride" name="dateofride">
                        </label>
                    </div>
                    <div class="form-row">
                        <label>
                            <span>Message</span>
                            <textarea name="message" placeholder="Enter Message" id="id_message"></textarea>
                        </label>
                    </div>
                    <div class="form-row">
                        <label>
                            <span>Source Location</span>
                            <input type="text" name="source_location" maxlength="1000" required="" placeholder="Select Location Below" id="id_source_location">
                        </label>
                    </div>
                    <button type="button" id="source_location_button" style="margin-top: -20px;" data-toggle="modal" data-target="#myModal">Source</button>
                    <div class="form-row">
                        <label>
                            <span>Destination Location</span>
                            <input type="text" name="destination_location" maxlength="1000" required="" placeholder="Select Location Below" id="id_destination_location">
                        </label>
                    </div>
                    <button type="button" id="destination_location_button" style="margin-top: -20px;" data-toggle="modal" data-target="#myModal">Destination</button>
                    <div class="form-row">
                        <button type="submit" class="btn">Submit</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="modal fade" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <h4 class="modal-title">Select Location</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <div class="pac-card" id="pac-card">
                        <div id="pac-container">
                            <input id="location_input" type="text" placeholder="Enter a location">
                        </div>
                    </div>
                    <div id="map"></div>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

CarzRideOn/templates/website/request_ride.html
{% extends 'website/base.html' %}

{% block content %}
    <div class="container padded-container">
        <form class="form-login" method="post" action="">
            {% csrf_token %}
            <div class="form-log-in-with-email">
                <div class="form-white-background">
                    <div class="form-title-row">
                        <h1>Request Ride from {{ selected_ride_owner }}</h1>
                    </div>
                    <div class="form-row">
                        <label>
                            <span>Message</span>
                            <input type="text" name="message" maxlength="1000" id="id_message">
                        </label>
                    </div>
                    <div class="form-row">
                        <button type="submit" class="btn">Submit</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

CarzRideOn/templates/website/takeride.html
{% extends 'website/base.html' %}
{% block content %}
    <div class="container padded-container">
        <form class="form-login" method="post" action="#" id="offerrideform">
            {% csrf_token %}
            {% for field in form %}
                {% if "lati" in field.label_tag or "long" in field.label_tag %}
                    <div class="input-group">
                        {{ field.as_hidden }}
                    </div>
                {% endif %}
            {% endfor %}
            <div class="form-log-in-with-email">
                <div class="form-white-background">
                    <div class="form-title-row">
                        <h1>Take Ride</h1>
                    </div>
                    <div class="form-row">
                        <label>
                            <span>Source Location</span>
                            <input type="text" name="source_location" maxlength="1000" required="" placeholder="Select Location Below" id="id_source_location">
                        </label>
                    </div>
                    <button type="button" id="source_location_button_take_ride" style="margin-top: -20px;" data-toggle="modal" data-target="#myModal2">Source</button>
                    <div class="form-row">
                        <label>
                            <span>Destination Location</span>
                            <input type="text" name="destination_location" maxlength="1000" required="" placeholder="Select Location Below" id="id_destination_location">
                        </label>
                    </div>
                    <button type="button" id="destination_location_button_take_ride" style="margin-top: -20px;" data-toggle="modal" data-target="#myModal2">Destination</button>
                    <div class="form-row">
                        <button type="submit" class="btn">Submit</button>
                    </div>
                </div>
            </div>
        </form>
    </div>


    <div class="modal fade" id="myModal2">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <h4 class="modal-title">Select Location</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <div class="pac-card" id="pac-card">
                        <div id="pac-container">
                            <input id="location_input" type="text" placeholder="Enter a location">
                        </div>
                    </div>
                    <div id="map"></div>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>

            </div>
        </div>
    </div>


{% endblock %}

CarzRideOn/templates/website/update_profile.html
{% extends 'website/base.html' %}
{% block content %}
    <div class="container padded-container">
        <form class="form-login" method="post" action="#">
            {% csrf_token %}
            <div class="form-log-in-with-email">
                <div class="form-white-background">
                    <div class="form-title-row">
                        <h1>Update Profile</h1>
                    </div>
                    {% for field in form %}
                        {% if "Fcm" in field.label_tag %}
                            <div class="input-group">
                                {{ field.as_hidden }}
                            </div>
                        {% elif "Gender" in field.label_tag %}
                             <div class="form-row">
                                <label>
                                    <span>Gender</span>
                                    <select name="gender" id="id_gender">
                                        <option selected>Select Gender</option>
                                        <option value="Male">Male</option>
                                        <option value="Female">Female</option>
                                    </select>
                                </label>
                            </div>
                        {% elif "Dob" in field.label_tag %}
                             <div class="form-row">
                                <label>
                                    <span>{{ field.label_tag }}</span>
                                    <input type="date" id="{{ field.id_for_label }}" name="{{ field.name }}" placeholder="Enter {{ field.label }}">
                                </label>
                            </div>
                        {% else %}
                            <div class="form-row">
                                <label>
                                    <span>{{ field.label_tag }}</span>
                                    <input type="text" id="{{ field.id_for_label }}" name="{{ field.name }}" placeholder="Enter {{ field.label }}">
                                </label>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <div class="form-row">
                        <button type="submit" class="btn">Submit</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

CarzRideOn/templates/website/validate_request.html
{% extends 'website/base.html' %}

{% block content %}

    <div class="container">
        <div class="heading-text">
            Validate Request from {{ request_owner }}
        </div>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>


{% endblock %}

CarzRideOn/templates/website/view_request.html
{% extends 'website/base.html' %}

{% block content %}

    <div class="container">
        <div class="heading-text">
            Pending Ride Requests
        </div>
        {% if requests %}
            {% for ride_request in requests %}
                {{ ride_request.fb_id }}
                <a href="{% url 'validate_ride_request' ride_request.id%}" class="btn btn-primary">Validate Request</a>
            {% endfor %}
        {% else %}
            <h2>You have no pending requests.</h2>
        {% endif %}
    </div>


{% endblock %}